### ISSUE TITLE
Modify Installation and setup steps

### ISSUE THREAD

**Issue by fokosun** [teamtaverna/slack_integration#14]
mkvirtualenv -p python3 <envname>

After this line, though it's pretty obvious, i think we should add that the contributor should `cd` into the `<envname>` created before running the next command to install the requirements.

**Comment by kosyfrances** [comment]
@andela-fokosun if the contributor uses virtualenvwrapper, there would be no need to `cd` into `<envname>` as the virtualenv would be automatically activated upon creation. I would be closing this issue.
