### ISSUE TITLE
Comments in reviews should not be a list of strings

### ISSUE THREAD

**Issue by kosyfrances** [teamtaverna/slack_integration#44]
Currently, we are sending back comments to the api as a list of strings and on the admin dashboard  it looks like this 
![screen shot 2017-11-07 at 12 38 49 pm](https://user-images.githubusercontent.com/10073270/32491903-a6f0ce02-c3b8-11e7-97f9-fd9d1b642d17.png)

**Comment by iamlordaubrey** [comment]
Checking this out.

**Comment by kosyfrances** [comment]
#45 merged
